/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj2lojaonlineui;

import BLL.CorBLL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import proj2lojaonline.DAL.Cor;
import proj2lojaonlineui.CoresUI.CriarCorUI;
import proj2lojaonlineui.CoresUI.EditarCoresUI;
import proj2lojaonlineui.CoresUI.ExcluirCorUI;
import proj2lojaonlineui.CoresUI.ListarCoresUI;
import proj2lojaonlineui.Generos.CriarGenerosUI;
import proj2lojaonlineui.Generos.EditarGeneroUI;
import proj2lojaonlineui.Generos.ListarGeneroUI;
import proj2lojaonlineui.Produto.CriarProduto;
import proj2lojaonlineui.Produto.ListarProduto;
import proj2lojaonlineui.TamanhosUI.CriarTam;
import proj2lojaonlineui.TamanhosUI.EditarTam;
import proj2lojaonlineui.TamanhosUI.ListarTamanho;
import proj2lojaonlineui.TipoUI.CriarTipo;
import proj2lojaonlineui.TipoUI.EditarTipo;
import proj2lojaonlineui.TipoUI.ListarTipoUI;

/**
 *
 * @author marci
 */
public class GestorEstoque extends javax.swing.JFrame {

    JPanel painelVisivel = null;

    /**
     * Creates new form MainJFrame
     */
    public GestorEstoque() {
        initComponents();
        this.painelVisivel = this.mainPanelE;
        this.setContentPane(this.painelVisivel);
        this.repaint();
// List<Cor> listaCores = null;

//        listaCores = CorBLL.readAll();
//           ArrayList<String> cores = new ArrayList<String>();
//        for(Cor cor1 : listaCores){
//           cores.add( cor1.getNome());
//                  
//            jComboBox1.addItem(cor1.getNome());
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        mainPanelE = new javax.swing.JPanel();
        LetreiroLoja = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LocalMenuPrincipal = new javax.swing.JMenuBar();
        Produtos = new javax.swing.JMenu();
        CriarProd = new javax.swing.JMenuItem();
        EditarProd = new javax.swing.JMenuItem();
        ListarProd = new javax.swing.JMenuItem();
        Cores = new javax.swing.JMenu();
        CriarCor = new javax.swing.JMenuItem();
        EditarCor = new javax.swing.JMenuItem();
        ListarCor = new javax.swing.JMenuItem();
        Generos = new javax.swing.JMenu();
        CriarGen = new javax.swing.JMenuItem();
        EditarGen = new javax.swing.JMenuItem();
        ListarGen = new javax.swing.JMenuItem();
        Tamanhos = new javax.swing.JMenu();
        CriarTam = new javax.swing.JMenuItem();
        EditarTam = new javax.swing.JMenuItem();
        ListarTam = new javax.swing.JMenuItem();
        Tipos = new javax.swing.JMenu();
        CriarTipo = new javax.swing.JMenuItem();
        EditarTipo = new javax.swing.JMenuItem();
        ListarTipo = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LetreiroLoja.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LetreiroLoja.setText("Loja pronto a vestir online");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("NA COR DA ESTAÇÃO, Lda");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Sessão Gestor de Estoque");

        javax.swing.GroupLayout mainPanelELayout = new javax.swing.GroupLayout(mainPanelE);
        mainPanelE.setLayout(mainPanelELayout);
        mainPanelELayout.setHorizontalGroup(
            mainPanelELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelELayout.createSequentialGroup()
                .addGroup(mainPanelELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelELayout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(LetreiroLoja))
                    .addGroup(mainPanelELayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel1))
                    .addGroup(mainPanelELayout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabel2)))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        mainPanelELayout.setVerticalGroup(
            mainPanelELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelELayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addGap(105, 105, 105)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(LetreiroLoja)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        Produtos.setText("Produto");
        Produtos.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutosActionPerformed(evt);
            }
        });

        CriarProd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CriarProd.setText("Criar Produto");
        CriarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarProdActionPerformed(evt);
            }
        });
        Produtos.add(CriarProd);

        EditarProd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EditarProd.setText("Editar Produto");
        EditarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarProdActionPerformed(evt);
            }
        });
        Produtos.add(EditarProd);

        ListarProd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ListarProd.setText("Listar Produtos");
        ListarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarProdActionPerformed(evt);
            }
        });
        Produtos.add(ListarProd);

        LocalMenuPrincipal.add(Produtos);

        Cores.setText("Cor");
        Cores.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        CriarCor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CriarCor.setText("Criar Cor");
        CriarCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarCorActionPerformed(evt);
            }
        });
        Cores.add(CriarCor);

        EditarCor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EditarCor.setText("Editar Cor");
        EditarCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarCorActionPerformed(evt);
            }
        });
        Cores.add(EditarCor);

        ListarCor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ListarCor.setText("Listar Cores");
        ListarCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarCorActionPerformed(evt);
            }
        });
        Cores.add(ListarCor);

        LocalMenuPrincipal.add(Cores);

        Generos.setText("Gênero");
        Generos.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        CriarGen.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CriarGen.setText("Criar Gênero");
        CriarGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarGenActionPerformed(evt);
            }
        });
        Generos.add(CriarGen);

        EditarGen.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EditarGen.setText("Editar Gênero");
        EditarGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarGenActionPerformed(evt);
            }
        });
        Generos.add(EditarGen);

        ListarGen.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ListarGen.setText("Listar Gêneros");
        ListarGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarGenActionPerformed(evt);
            }
        });
        Generos.add(ListarGen);

        LocalMenuPrincipal.add(Generos);

        Tamanhos.setText("Tamanho");
        Tamanhos.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        CriarTam.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CriarTam.setText("Criar Tamanho");
        CriarTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarTamActionPerformed(evt);
            }
        });
        Tamanhos.add(CriarTam);

        EditarTam.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EditarTam.setText("Editar Tamanho");
        EditarTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarTamActionPerformed(evt);
            }
        });
        Tamanhos.add(EditarTam);

        ListarTam.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ListarTam.setText("Listar Tamanhos");
        ListarTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarTamActionPerformed(evt);
            }
        });
        Tamanhos.add(ListarTam);

        LocalMenuPrincipal.add(Tamanhos);

        Tipos.setText("Tipo");
        Tipos.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        CriarTipo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CriarTipo.setText("Criar Tipo");
        CriarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarTipoActionPerformed(evt);
            }
        });
        Tipos.add(CriarTipo);

        EditarTipo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EditarTipo.setText("Editar Tipo");
        EditarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarTipoActionPerformed(evt);
            }
        });
        Tipos.add(EditarTipo);

        ListarTipo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ListarTipo.setText("Listar Tipos");
        ListarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarTipoActionPerformed(evt);
            }
        });
        Tipos.add(ListarTipo);

        LocalMenuPrincipal.add(Tipos);

        setJMenuBar(LocalMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanelE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanelE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CriarCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarCorActionPerformed
        // TODO add your handling code here:
        CriarCorUI criar = new CriarCorUI();
        criar.setVisible(true);
    }//GEN-LAST:event_CriarCorActionPerformed

    private void ListarTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarTamActionPerformed
        // TODO add your handling code here:
        this.painelVisivel.removeAll();

        this.painelVisivel.setVisible(false);
        ListarTamanho listarTamanhos = new ListarTamanho();
        this.painelVisivel = listarTamanhos;

        this.painelVisivel.setVisible(true);
        this.setContentPane(this.painelVisivel);
        this.repaint();
    }//GEN-LAST:event_ListarTamActionPerformed

    private void ListarCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarCorActionPerformed
        // TODO add your handling code here:
        this.painelVisivel.removeAll();

        this.painelVisivel.setVisible(false);
        ListarCoresUI listaCores = new ListarCoresUI();
        this.painelVisivel = listaCores;

        this.painelVisivel.setVisible(true);
        this.setContentPane(this.painelVisivel);
        this.repaint();


    }//GEN-LAST:event_ListarCorActionPerformed

    private void EditarCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarCorActionPerformed
// TODO add your handling code here:
        this.painelVisivel.removeAll();

        this.painelVisivel.setVisible(false);

        EditarCoresUI editaCores = new EditarCoresUI();
        this.painelVisivel = editaCores;

        this.painelVisivel.setVisible(true);
        this.setContentPane(this.painelVisivel);
        this.repaint();

    }//GEN-LAST:event_EditarCorActionPerformed

    private void CriarTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarTamActionPerformed
//         TODO add your handling code here:
        CriarTam criar = new CriarTam();
        criar.setVisible(true);
//        this.painelVisivel.removeAll();
//        this.painelVisivel.setVisible(false);
//        CriarTamUI criarTam = new CriarTamUI();
//        this.painelVisivel = criarTam;
//
//        this.painelVisivel.setVisible(true);
//        this.setContentPane(this.painelVisivel);
//        this.repaint();

//         
    }//GEN-LAST:event_CriarTamActionPerformed

    private void CriarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarTipoActionPerformed
        // TODO add your handling code here:

        CriarTipo criarTipo = new CriarTipo();
        criarTipo.setVisible(true);


    }//GEN-LAST:event_CriarTipoActionPerformed

    private void ListarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarTipoActionPerformed
        // TODO add your handling code here:
        this.painelVisivel.setVisible(false);
        ListarTipoUI listaTipos = new ListarTipoUI();

        this.painelVisivel = listaTipos;

        this.painelVisivel.setVisible(true);
        this.setContentPane(this.painelVisivel);
        this.repaint();
    }//GEN-LAST:event_ListarTipoActionPerformed

    private void EditarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarProdActionPerformed

    private void ListarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarProdActionPerformed
        // TODO add your handling code here:
        this.painelVisivel.setVisible(false);
        ListarProduto listaProdutos = new ListarProduto();

        this.painelVisivel = listaProdutos;

        this.painelVisivel.setVisible(true);
        this.setContentPane(this.painelVisivel);
        this.repaint();
    }//GEN-LAST:event_ListarProdActionPerformed

    private void EditarTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarTamActionPerformed
        // TODO add your handling code here:

        this.painelVisivel.setVisible(false);

        EditarTam editarTamanho = new EditarTam();
        this.painelVisivel = editarTamanho;

        this.painelVisivel.setVisible(true);
        this.setContentPane(this.painelVisivel);
        this.repaint();
//         EditarTam editar = new EditarTam();
//        editar.setVisible(true);

    }//GEN-LAST:event_EditarTamActionPerformed

    private void CriarGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarGenActionPerformed
        // TODO add your handling code here:
        CriarGenerosUI criarGen = new CriarGenerosUI();
        criarGen.setVisible(true);
    }//GEN-LAST:event_CriarGenActionPerformed

    private void EditarGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarGenActionPerformed
        // TODO add your handling code here:
        this.painelVisivel.setVisible(false);
        EditarGeneroUI editarGeneros = new EditarGeneroUI();

        this.painelVisivel = editarGeneros;

        this.painelVisivel.setVisible(true);
        this.setContentPane(this.painelVisivel);
        this.repaint();
    }//GEN-LAST:event_EditarGenActionPerformed

    private void ListarGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarGenActionPerformed
        // TODO add your handling code here:
        this.painelVisivel.setVisible(false);
        ListarGeneroUI tipo = new ListarGeneroUI();

        this.painelVisivel = tipo;

        this.painelVisivel.setVisible(true);
        this.setContentPane(this.painelVisivel);
        this.repaint();
    }//GEN-LAST:event_ListarGenActionPerformed

    private void EditarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarTipoActionPerformed
        // TODO add your handling code here:
        this.painelVisivel.setVisible(false);
        EditarTipo editarTipos = new EditarTipo();

        this.painelVisivel = editarTipos;

        this.painelVisivel.setVisible(true);
        this.setContentPane(this.painelVisivel);
        this.repaint();
    }//GEN-LAST:event_EditarTipoActionPerformed

    private void ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ProdutosActionPerformed

    private void CriarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarProdActionPerformed
        // TODO add your handling code here:
        CriarProduto criarProd = new CriarProduto();
        criarProd.setVisible(true);

    }//GEN-LAST:event_CriarProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestorEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestorEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestorEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestorEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestorEstoque().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cores;
    private javax.swing.JMenuItem CriarCor;
    private javax.swing.JMenuItem CriarGen;
    private javax.swing.JMenuItem CriarProd;
    private javax.swing.JMenuItem CriarTam;
    private javax.swing.JMenuItem CriarTipo;
    private javax.swing.JMenuItem EditarCor;
    private javax.swing.JMenuItem EditarGen;
    private javax.swing.JMenuItem EditarProd;
    private javax.swing.JMenuItem EditarTam;
    private javax.swing.JMenuItem EditarTipo;
    private javax.swing.JMenu Generos;
    private javax.swing.JLabel LetreiroLoja;
    private javax.swing.JMenuItem ListarCor;
    private javax.swing.JMenuItem ListarGen;
    private javax.swing.JMenuItem ListarProd;
    private javax.swing.JMenuItem ListarTam;
    private javax.swing.JMenuItem ListarTipo;
    private javax.swing.JMenuBar LocalMenuPrincipal;
    private javax.swing.JMenu Produtos;
    private javax.swing.JMenu Tamanhos;
    private javax.swing.JMenu Tipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel mainPanelE;
    // End of variables declaration//GEN-END:variables
}
