/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj2lojaonlineui.CoresUI;




import BLL.CorBLL;
import java.sql.SQLException;
import proj2lojaonline.DAL.Cor;

/**
 *
 * @author marci
 */
public class CriarCorUI extends javax.swing.JFrame {

    int modoOper = 0; //0-Criar; 1- Update; 2- Delete
    Cor cor1ToUpdte = null;
    Cor cor1ToDelete =  null;
    /**
     * Creates new form CriarCorUI
     */
    public CriarCorUI() {
        initComponents();
    }

    public CriarCorUI(Cor cor1) {

        //Alterar Cor
        initComponents();

        this.CriarCor.setText("Editar Cor - codCor " + cor1.getCodcor());
        this.escreverCor.setText(cor1.getNome());
        
       this.modoOper = 1;
        cor1ToUpdte = cor1;
        
        this.escreverCor.setText(cor1.getNome());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCriarCor = new javax.swing.JPanel();
        Nome = new javax.swing.JLabel();
        escreverCor = new javax.swing.JTextField();
        feedbackMessage = new javax.swing.JLabel();
        OK = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        CriarCor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Nome.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Nome.setText("Nome:");

        escreverCor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        escreverCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escreverCorActionPerformed(evt);
            }
        });

        feedbackMessage.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        OK.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        OK.setText("CONFIRMAR");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        Cancelar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Cancelar.setText("CANCELAR");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCriarCorLayout = new javax.swing.GroupLayout(PanelCriarCor);
        PanelCriarCor.setLayout(PanelCriarCorLayout);
        PanelCriarCorLayout.setHorizontalGroup(
            PanelCriarCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCriarCorLayout.createSequentialGroup()
                .addGroup(PanelCriarCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCriarCorLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(Nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(escreverCor, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCriarCorLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(feedbackMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(290, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCriarCorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OK)
                .addGap(101, 101, 101)
                .addComponent(Cancelar)
                .addGap(100, 100, 100))
        );
        PanelCriarCorLayout.setVerticalGroup(
            PanelCriarCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCriarCorLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(PanelCriarCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome)
                    .addComponent(escreverCor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(feedbackMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(PanelCriarCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OK, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        CriarCor.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        CriarCor.setText("Criar Cor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(CriarCor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(PanelCriarCor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(CriarCor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelCriarCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        // TODO add your handling code here:

        if (modoOper == 0) {
            Cor cor = new Cor();
            cor.setNome(escreverCor.getText());

            CorBLL.create(cor);

            feedbackMessage.setText("COR CRIADA COM SUCESSO!");
            escreverCor.setText("");
            
        }
        else if (modoOper == 1){
            //Modo Update
            cor1ToUpdte.setNome(escreverCor.getText());
            
            CorBLL.update(cor1ToUpdte);
            feedbackMessage.setText("COR EDITADA COM SUCESSO!");
            escreverCor.setText("");
          
        }
        else{
            //Modo Delete
            cor1ToDelete.setNome(escreverCor.getText());
            
            try{
                CorBLL.delete(cor1ToDelete);
                feedbackMessage.setText("COR EXCLUIDA COM SUCESSO!");
            }
            catch(Exception ex){
                feedbackMessage.setText("ERRO! Cor Não pode ser Apagada!");
            }
            
            escreverCor.setText("");
        }
        
        
        
        
       
    }//GEN-LAST:event_OKActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        this.show(false);
    }//GEN-LAST:event_CancelarActionPerformed

    private void escreverCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escreverCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escreverCorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarCorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarCorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarCorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarCorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarCorUI().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel CriarCor;
    private javax.swing.JLabel Nome;
    private javax.swing.JButton OK;
    private javax.swing.JPanel PanelCriarCor;
    private javax.swing.JTextField escreverCor;
    private javax.swing.JLabel feedbackMessage;
    // End of variables declaration//GEN-END:variables
}
