/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj2lojaonlineui.CoresUI;

import BLL.CorBLL;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import proj2lojaonline.DAL.Cor;

/**
 *
 * @author marci
 */
public class EditarCoresUI extends javax.swing.JPanel {

    /**
     * Creates new form EditarCoresUI
     */
    public EditarCoresUI() {
        initComponents();
        List<Cor> listaCores = null;
        
        DefaultTableModel tmodel = (DefaultTableModel)jTable1_EditarCor.getModel();
        
        listaCores = CorBLL.readAll();
        
        for(Cor cor1 : listaCores){
            String[] linhaTabela = new String[2];
            linhaTabela[0] = cor1.getCodcor().toString();
            linhaTabela[1] = cor1.getNome();
            
            tmodel.addRow(linhaTabela);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_EditarCor = new javax.swing.JTable();
        SAIR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Editar Cores");

        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jScrollPane1MousePressed(evt);
            }
        });

        jTable1_EditarCor.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTable1_EditarCor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "codCor", "nome"
            }
        ));
        jTable1_EditarCor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1_EditarCorMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_EditarCor);

        SAIR.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        SAIR.setText("SAIR");
        SAIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SAIRMousePressed(evt);
            }
        });
        SAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIRActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Selecione a cor a editar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SAIR, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(SAIR, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MousePressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jScrollPane1MousePressed

    private void jTable1_EditarCorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_EditarCorMousePressed
        // TODO add your handling code here:
        int linha = this.jTable1_EditarCor.getSelectedRow();
        int codCor = Integer.parseInt((String) ((DefaultTableModel) this.jTable1_EditarCor.getModel()).getValueAt(linha, 0));

        Cor cor1 = CorBLL.read(codCor);

        CriarCorUI updateCor = new CriarCorUI(cor1);
        updateCor.setVisible(true);
        
       
    }//GEN-LAST:event_jTable1_EditarCorMousePressed

    private void SAIRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAIRMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SAIRMousePressed

    private void SAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIRActionPerformed
        // TODO add your handling code here:
        this.show(false);
        
        
    }//GEN-LAST:event_SAIRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SAIR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_EditarCor;
    // End of variables declaration//GEN-END:variables
}
