/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj2lojaonlineui.CoresUI;

import BLL.CorBLL;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import proj2lojaonline.DAL.Cor;

/**
 *
 * @author marci
 */
public class ListarCoresUI extends javax.swing.JPanel {

    /**
     * Creates new form ListarCoresUI
     */
    public ListarCoresUI() {
        initComponents();
        
        List<Cor> listaCores = null;
        
        DefaultTableModel tmodel = (DefaultTableModel)jTable1_ListarCor.getModel();
        
        listaCores = CorBLL.readAll();
        
        for(Cor cor1 : listaCores){
            String[] linhaTabela = new String[2];
            linhaTabela[0] = cor1.getCodcor().toString();
            linhaTabela[1] = cor1.getNome();
            
            tmodel.addRow(linhaTabela);
                
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_ListarCor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        SAIR = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(873, 513));

        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTable1_ListarCor.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTable1_ListarCor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] { },
            new String [] {
                "codCor", "nome"
            }
        ));
        jTable1_ListarCor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1_ListarCorMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_ListarCor);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Listar Cores");
        jLabel1.setMaximumSize(new java.awt.Dimension(183, 43));
        jLabel1.setMinimumSize(new java.awt.Dimension(183, 43));
        jLabel1.setPreferredSize(new java.awt.Dimension(183, 43));

        SAIR.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        SAIR.setText("SAIR");
        SAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SAIR)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(SAIR, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jTable1_ListarCorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_ListarCorMousePressed
//         TODO add your handling code here:
          int linha = this.jTable1_ListarCor.getSelectedRow();
        int codCor = Integer.parseInt((String) ((DefaultTableModel)this.jTable1_ListarCor.getModel() ).getValueAt(linha, 0));
        
        Cor cor1 = CorBLL.read(codCor);
//        
//        CriarCorUI updateCor = new CriarCorUI(cor1);
//        updateCor.setVisible(true);
        
    }//GEN-LAST:event_jTable1_ListarCorMousePressed

    private void SAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIRActionPerformed
        // TODO add your handling code here:
        this.show(false);
    }//GEN-LAST:event_SAIRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SAIR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_ListarCor;
    // End of variables declaration//GEN-END:variables
}
