/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj2lojaonlineui.Generos;

import BLL.GeneroBLL;
import proj2lojaonline.DAL.Genero;

/**
 *
 * @author marci
 */
public class CriarGenerosUI extends javax.swing.JFrame {

    int modoOper = 0; //0-Criar; 1- Update
    Genero genToUpdte = null;
    /**
     * Creates new form CriarGenerosUI
     */
    public CriarGenerosUI() {
        initComponents();
        
    }
        
     public CriarGenerosUI(Genero genero) {
        initComponents();
        
        
        this.CriarGenero.setText("Editar genero - codGenero " + genero.getCodgenero());
        this.escreverNomeGen.setText(genero.getNome());
        
       this.modoOper = 1;
        genToUpdte = genero;
//        
        this.escreverNomeGen.setText(genero.getNome());
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CriarGenero = new javax.swing.JLabel();
        PanelCriarGenero = new javax.swing.JPanel();
        Nome = new javax.swing.JLabel();
        escreverNomeGen = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        feedbackMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CriarGenero.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        CriarGenero.setText("Criar Gênero");

        Nome.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Nome.setText("Nome:");

        escreverNomeGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escreverNomeGenActionPerformed(evt);
            }
        });

        ok.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ok.setText("CONFIRMAR");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        Cancelar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Cancelar.setText("CANCELAR");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        feedbackMessage.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout PanelCriarGeneroLayout = new javax.swing.GroupLayout(PanelCriarGenero);
        PanelCriarGenero.setLayout(PanelCriarGeneroLayout);
        PanelCriarGeneroLayout.setHorizontalGroup(
            PanelCriarGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCriarGeneroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ok)
                .addGap(82, 82, 82)
                .addComponent(Cancelar)
                .addGap(108, 108, 108))
            .addGroup(PanelCriarGeneroLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCriarGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(escreverNomeGen, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelCriarGeneroLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(feedbackMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        PanelCriarGeneroLayout.setVerticalGroup(
            PanelCriarGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCriarGeneroLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PanelCriarGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome)
                    .addComponent(escreverNomeGen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(feedbackMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(PanelCriarGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CriarGenero)
                    .addComponent(PanelCriarGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(CriarGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelCriarGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        this.show(false);
    }//GEN-LAST:event_CancelarActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        if (modoOper == 0) {
            Genero genero = new Genero();
            genero.setNome(escreverNomeGen.getText());

            GeneroBLL.create(genero);

            feedbackMessage.setText("GENERO CRIADO COM SUCESSO!");
            escreverNomeGen.setText("");

        }else{
            //Modo Update
            genToUpdte.setNome(escreverNomeGen.getText());

            GeneroBLL.update(genToUpdte);
            feedbackMessage.setText("GENERO ATUALIZADO COM SUCESSO!");
            escreverNomeGen.setText("");
        }
    }//GEN-LAST:event_okActionPerformed

    private void escreverNomeGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escreverNomeGenActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_escreverNomeGenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarGenerosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarGenerosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarGenerosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarGenerosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarGenerosUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel CriarGenero;
    private javax.swing.JLabel Nome;
    private javax.swing.JPanel PanelCriarGenero;
    private javax.swing.JTextField escreverNomeGen;
    private javax.swing.JLabel feedbackMessage;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
}
